### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by andorfermichael** [Alvw/EdfLib#1]
Hi,

I am currently developing an Android ECG application which should also store received data in EDF format.

Thus, I was very happy to see that someone has written an EdfLib in Java. 

Unfortunately, you do not provide a license which results in the situation that your project must not be used by anyone even if it is publicly available.

So, I would like to ask you if you would allow me to use your code and maybe add a license file so that anyone else can be sure what the license state of your project is.

**Comment by galafit** [comment]
Yes of course... it is open and free anyone may use it and change. We add
license this days

2017-03-07 16:52 GMT+01:00 Michael Andorfer <notifications@github.com>:

**Comment by galafit** [comment]
Mit License was added
