### ISSUE TITLE
Question: Real-Time Sample Writing

### ISSUE THREAD

**Issue by andorfermichael** [Alvw/EdfLib#2]
Hi,

I would like to know if it is possible to continously write samples to an EDF file. If yes, what would be the best way to do this?

In my case, I receive a data packet with X samples in it from a Bluetooth Serial device (each 500ms). I am using observer pattern to get informed when new samples (data packet) received and then I would like to write those data immediately to the EDF file.

Do I have to create a new file where the old and the new samples are merged?

**Comment by galafit** [comment]
Of course you can continously write samples to an EDF file (please download new version... some changes was made).

EdfWriter edfFileWriter = new EdfWriter("filename");

Then in the HeaderConfig describe your data packet (data record). For
example if you have X samples from one channel every 500ms

HeaderConfig headerConfig = new HeaderConfig(1); // 1 channel
headerConfig.setDurationOfDataRecord(0.5); // 500ms = 0.5second
headerConfig.setNumberOfSamplesInEachDataRecord(0, X); // channels numbering begins from 0
headerConfig.setPhysicalMin(0, physical min);
headerConfig.setPhysicalMax(0, physical max);
headerConfig.setPhysicalDimension(0,"uV or whatsever");

Open edfFileWriter with the created headerConfig

edfFileWriteredfFileWriter.open(headerConfig);

And after that when you receive every data packet with X samples just write it:

edfFileWriter.writeDigitalSamples(array of X samples);

or if you receive not digital but physical samples:

edfFileWriter.writePhysicalSamples(array of X samples);

Important! When you finish  your writing job close the writer

edfFileWriter.close();

Just in case... Here a link to another java EdfLib -
https://github.com/MIOB/EDF4J


2017-03-11 19:27 GMT+01:00 Michael Andorfer <notifications@github.com>:

**Comment by andorfermichael** [comment]
Thank you! :)
